# Generated by Django 3.1.5 on 2021-01-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
